### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by stennettm** [jonschlinkert/delete#3]
In v0.3.0 it was possible to call the async del method without a callback, in v0.3.1 this throws an error due to the callback being undefined.

I can provide a pull request if desired.

**Comment by doowb** [comment]
I don't think it was intentional for the async method to be used without a callback. This was a side effect of passing the callback directly into `async.each`. I think this was a bug that was fixed since the documented example in the readme shows passing in a callback.

I don't think we should allow not passing in the callback since this can lead to more errors and hard to track down bugs. But to keep from breaking code written without the callback, we should probably bump to `0.4.0`.

**Comment by stennettm** [comment]
Makes sense, +1 to a minor version bump.

**Comment by jonschlinkert** [comment]
Ok, so I'll need to add some code to emulate 0.3.0, publish to 0.3.2 then bump to 0.4.0. How about if I do this in the `del` function for the 0.3.2 code:

```js

function del(patterns, options, cb) {
  if (typeof options === 'function') {
    cb = options;
    options = {};
  }
  // if no callback is given, return the sync method
  if (typeof cb !== 'function') {
    return del.sync.apply(del, arguments);
  }

  // ...
}
```

**Comment by tunnckoCore** [comment]
@jonschlinkert yea looks good
